services:
    - docker

before_script:
    - docker-compose run composer install --ignore-platform-reqs

script:
    - docker-compose run php-fpm vendor/bin/phpstan.phar analyse -l 5 -c phpstan.neon app
