services:
    - docker

install:
    - docker-compose run composer install --ignore-platform-reqs

before_script:
    - docker-compose build php-fpm

script:
    - docker-compose run php-fpm vendor/bin/phpstan.phar analyse -l 7 app
