version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
          - 80
        volumes:
          - ./:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
          - php-fpm
        restart: on-failure

    php-fpm:
        build: ./docker/php-fpm
        volumes:
          - ./:/var/www
        expose:
          - 9000
        working_dir: /var/www
        restart: on-failure

    composer:
        image: composer:latest
        command: install --ignore-platform-reqs --no-dev
        volumes:
          - ./:/var/www
        working_dir: /var/www

    webpack:
        image: node:alpine
        command: sh -cl "yarn install --ignore-engines && yarn run webpack --production"
        volumes:
          - ./:/var/www
        working_dir: /var/www
